# Generated by Django 5.2.12 on 2026-03-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
