# Generated by Django 5.2.12 on 2026-05-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_user_phone_number_user_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist_name',
            field=models.CharField(default='Unknown Artist', max_length=200),
            preserve_default=False,
        ),
    ]
